services:
  mysql:
    image: mysql:latest
    platform: linux/arm64/v8  # ARM64 아키텍처를 명시적으로 설정
    container_name: mysql-local
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sakila
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/mysql-sakila-schema.sql:/docker-entrypoint-initdb.d/1_init.sql:ro
      - ./sql/mysql-sakila-insert-data.sql:/docker-entrypoint-initdb.d/2_data.sql:ro

volumes:
  mysql_data: